#*************************************************************************************************************************************************************
#--------------------------------------------------------------------- SENSORS ------------------------------------------------------------------------------*
#*************************************************************************************************************************************************************


#*******************************************************************
#--------------- Homeassistant internal time & date ---------------*
#*******************************************************************
# Bukes feks. i "auotmations" for å trigge state endring basert på tid
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'date_time_utc'
    - 'date_time_iso'
    - 'time_date'
    - 'time_utc'
    - 'beat'

#*******************************************************************
#--------------- Home Assistant - Uptime --------------------------*
#*******************************************************************
- platform: uptime
  name: HA oppetid
